### ISSUE TITLE
Getting the pixel color from vertex to fragment shader

### ISSUE THREAD

**Issue by lesolorzanov** [thejohnhoffer/viaWebGL#9]
I am trying to process thr current view in openseadragon so that an image currently in greyscale can be mapped to any specified color. Can you tell me how to get each current pixel color so that I can calculate the appropriate new color in the fragment shader? I am a bit confused as to how to comunicate this information between shaders.

**Comment by Aiosa** [comment]
Hey, you really don't pass texture data onto a vertex shader. The vertex shader is for geometry, not fragment (texel/pixel) data. ViaGL uses vertex shader just to draw a simple square that will be covered with the texels later.

What you want is to just sample the tile being passed directly to fragment shader. I think there is no reason of doing anything inside the vertex shader, as the OSD interface is 2D anyway. I can't imagine using multiple 3D scenes on tiled layout.

Simply:

```
precision mediump float;
uniform sampler2D u_tile;
uniform vec2 u_tile_size;
varying vec2 v_tile_pos;

void main() {
  //sample the texel
  vec4 data = texture2D(u_tile, v_tile_pos);

 //use it to change the default value, e.g. you have grayscale: data = [0.3, 0.3, 0.3, 1] - map it to red only:
  gl_FragColor = vec4(data.r, .0, .0, data.a); //preserve transparency
}
```

You just need to learn how shaders work in more detail :) I think anyone can close this if you have proper rights to do so.

**Comment by lesolorzanov** [comment]
Thank you
